<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.11.0(352)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateAdminsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('admins', function (Blueprint $table) {
            $table->id();
            $table->integer('group_id');
            $table->string('name');
            $table->string('email', 50)->nullable();
            $table->string('password');
            $table->string('order_resolve_password', 50)->comment('补单密码');
            $table->string('authenticator_secret', 50)->comment('谷歌二步验证随机密钥');
            $table->tinyInteger('authenticator_status')->comment('二步验证状态，0关闭，1开启');
            $table->tinyInteger('status')->comment('0禁用，1启用');
            $table->string('remarks', 255)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('admins');
    }
}
